### ISSUE TITLE
Plugin not working with PyCharm 5.0.4

### ISSUE THREAD

**Issue by dklesev** [JustSid/AfterglowIntelliJ#12]
```
Plugin 'com.widerwille.afterglow' failed to initialize and will be disabled.  Please restart PyCharm.

com.intellij.diagnostic.PluginException: com/widerwille/afterglow/AfterglowTheme : Unsupported major.minor version 52.0 [Plugin: com.widerwille.afterglow]
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.UnsupportedClassVersionError: com/widerwille/afterglow/AfterglowTheme : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
    ... 30 more

```

**Comment by JustSid** [comment]
Afterglow uses Java 1.8 (for now particular reason to be honest, it just does), so you'll need to update your JVM. Since the IntelliJ platform is moving towards Java 1.8, I think there is not much point in changing this behaviour.
