### ISSUE TITLE
NullPointerException when opening some folders (v1.0.7)

### ISSUE THREAD

**Issue by beauchef** [JustSid/AfterglowIntelliJ#15]
I get a NullPointerException when opening some folders with v1.0.7 of Afterglow. I uninstalled the plug-in and re-installed it, with the same result:

`java.lang.NullPointerException
    at com.widerwille.afterglow.AfterglowIconCache.getIcon(AfterglowIconCache.java:51)
    at com.widerwille.afterglow.AfterglowProjectViewNodeDecorator.decorate(AfterglowProjectViewNodeDecorator.java:19)
    at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$1.run(AbstractPsiBasedNode.java:169)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
    at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:138)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
    at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
    at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:937)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
    at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:933)
    at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:885)
    at com.intellij.ide.util.treeView.AbstractTreeUi.collectNodesToInsert(AbstractTreeUi.java:2257)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$4600(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1394)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:45)
    at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.java:314)
    at org.jetbrains.concurrency.DonePromise.notify(DonePromise.java:88)
    at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2092)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$6000(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.perform(AbstractTreeUi.java:1984)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2187)
    at com.intellij.ide.util.treeView.AbstractTreeUi$37.perform(AbstractTreeUi.java:1979)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
    at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
    at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
    at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by JustSid** [comment]
This should be fixed in 04172c5, if you want, it would be nice if you could test this build with the fix included: http://cl.widerwille.com/febp

**Comment by beauchef** [comment]
No, I still get a NullPointerException, though elsewhere:

```
java.lang.NullPointerException
    at com.widerwille.afterglow.AfterglowIcons.getIcon(AfterglowIcons.java:146)
    at com.widerwille.afterglow.AfterglowIconCache.getIcon(AfterglowIconCache.java:62)
...
```

**Comment by JustSid** [comment]
Interesting... Can you try this version: http://cl.widerwille.com/fe0G ?

**Comment by beauchef** [comment]
Yes this one does not crash, and I can see the files that weren't appearing with 1.0.7. So it seems to work.

**Comment by JustSid** [comment]
Awesome, thank you very much! :)

**Comment by beauchef** [comment]
Should I uninstall this build, or will IntelliJ be intelligent enough to replace it when there is an official version?

**Comment by JustSid** [comment]
It'll be intelligent enough to figure out the new version when it's out and present you with the regular update dialogue.

**Comment by beauchef** [comment]
Excellent. Thanks for your time.
